baseURL = "https://www.xaegir.com"
languageCode = "en-us"
title = "XAEGIR | Coming Soon"
theme = "web"
removePathAccents = true


# HTML before the closing </head>
[params]
customHead = ""

# Navigation
[params.navigation]
logo = "images/logo.png"
home = "Home"
about = "About"
service = "Services"
contact = "Contact"

# Hero Area
[params.hero]
enable            = true
bg                = "images/header-bg.jpg"
title             = "An NFT Marketplace built just for you."
subtitle          = "Discover, collect, create and sell NFTs on a platform designed for your best experience. Cry havoc and ride the crypto seas."
btnText           = "Get Started"

# counter
disableCountdown  = false
countdownYear = "2022"
countdownMonth = "3"
countdownDay  = "10"

# About Section
[params.about]
enable      = true
heading     = "Xaegir - Experience & performance"
description = "Xaegir brings a fresh new look to the crypto markets. We are excited to work in this space and even more excited to bring new products and services to the community. Our focus is to bring innovation and growth to a thriving community, and with that goal in mind we have a long road ahead of us. It’s time to start executing on it. We will be launching our NFT marketplace at the end of Q1 2022, and we are looking forward to interacting with you all."

[[params.about.sliderItem]]
image   = "images/about/1.jpg"
[[params.about.sliderItem]]
image   = "images/about/2.jpg"
[[params.about.sliderItem]]
image   = "images/about/3.jpg"
[[params.about.sliderItem]]
image   = "images/about/4.jpg"


# Service Section
[params.service]
enable      = true
title       = "Immerse yourself in the Web3 Revolution"
subtitle    = "A decentralized marketplace with no single point of failure and censorship-resistant social media"
[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-strategy"
title   = "Vibrant Community"
description = "Xaegir will be reaching out to the community to find talent and receive input on how we can develop our platform for your best experience. We're counting on you to give us direction!"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-circle-compass"
title   = "Speed-Optimized"
description = "The entire platform has been built with the most performant and latest technologies. The Xaegir tech stack will enable your experience to greater heights, and take you even further into the crypto seas."
delay   = "0.2s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-anchor2"
title   = "Tons of Features"
description = "The initial release of the Xaegir platform will be focused on bringing the core features available in the market right now, but we are hard at work developing and integrating new features everyday."
delay   = "0.4s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-globe"
title   = "Limitless"
description = "We've designed our platform to scale immensely - to meet the growth of the community and be able to offer all new features and services at a moments notice."
delay   = "0.6s"

# Call to Action Section
[params.cta]
enable      = true
bg          = "images/call-to-action.jpg"
title       = "Subscribe to the Xaegir Newsletter"
subtitle    = "Keep up with news, promotions, and other events"

[params.contact]
enable      = true
title       = "Get In Touch"
subtitle    = "Interested in what we're doing? Are you talent that we need? Reach out - let's talk!"
